# Generated by Django 3.1.7 on 2021-03-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210314_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
