# Generated by Django 3.1.7 on 2021-03-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_remove_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='last_updated',
        ),
    ]
