# Generated by Django 3.1.7 on 2021-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_auto_20210324_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
