# Generated by Django 3.1.7 on 2021-03-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_topic_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='last_updated',
        ),
    ]
