# Generated by Django 3.1.7 on 2021-03-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_auto_20210325_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
